# Generated by Django 6.0.1 on 2026-01-11 16:37

import blogs.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_post_image_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=blogs.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=blogs.fields.EncryptedField(),
        ),
    ]
